#ifndef PICO_SDK_CONFIG_QMK_H
#define PICO_SDK_CONFIG_QMK_H

// Define this for all modules to prevent token pasting errors in pico/assert.h
// You can define them to 1 to enable assertions for a specific module if needed for debugging.
#ifndef PARAM_ASSERTIONS_ENABLED_PICO_TIMER
#define PARAM_ASSERTIONS_ENABLED_PICO_TIMER 0
#endif
#ifndef PARAM_ASSERTIONS_ENABLED_GPIO
#define PARAM_ASSERTIONS_ENABLED_GPIO 0
#endif
#ifndef PARAM_ASSERTIONS_ENABLED_ADC
#define PARAM_ASSERTIONS_ENABLED_ADC 0
#endif
#ifndef PARAM_ASSERTIONS_ENABLED_DMA
#define PARAM_ASSERTIONS_ENABLED_DMA 0
#endif
#ifndef PARAM_ASSERTIONS_ENABLED_I2C
#define PARAM_ASSERTIONS_ENABLED_I2C 0
#endif
#ifndef PARAM_ASSERTIONS_ENABLED_INTERP
#define PARAM_ASSERTIONS_ENABLED_INTERP 0
#endif
#ifndef PARAM_ASSERTIONS_ENABLED_IRQ
#define PARAM_ASSERTIONS_ENABLED_IRQ 0
#endif
#ifndef PARAM_ASSERTIONS_ENABLED_PIO
#define PARAM_ASSERTIONS_ENABLED_PIO 0
#endif
#ifndef PARAM_ASSERTIONS_ENABLED_PLL
#define PARAM_ASSERTIONS_ENABLED_PLL 0
#endif
#ifndef PARAM_ASSERTIONS_ENABLED_PWM
#define PARAM_ASSERTIONS_ENABLED_PWM 0
#endif
#ifndef PARAM_ASSERTIONS_ENABLED_RTC
#define PARAM_ASSERTIONS_ENABLED_RTC 0
#endif
#ifndef PARAM_ASSERTIONS_ENABLED_SPI
#define PARAM_ASSERTIONS_ENABLED_SPI 0
#endif
#ifndef PARAM_ASSERTIONS_ENABLED_SYSINFO
#define PARAM_ASSERTIONS_ENABLED_SYSINFO 0
#endif
#ifndef PARAM_ASSERTIONS_ENABLED_UART
#define PARAM_ASSERTIONS_ENABLED_UART 0
#endif
#ifndef PARAM_ASSERTIONS_ENABLED_XOSC
#define PARAM_ASSERTIONS_ENABLED_XOSC 0
#endif
#ifndef PARAM_ASSERTIONS_ENABLED_ROSC
#define PARAM_ASSERTIONS_ENABLED_ROSC 0
#endif
// Add any other PARAM_ASSERTIONS_ENABLED_xxxxxx that might be needed by other SDK parts.

// These are also used by pico/assert.h
#ifndef PARAM_ASSERTIONS_ENABLE_ALL
#define PARAM_ASSERTIONS_ENABLE_ALL 0
#endif
#ifndef PARAM_ASSERTIONS_DISABLE_ALL
#define PARAM_ASSERTIONS_DISABLE_ALL 0 // Set to 1 to disable all param assertions
#endif

#endif // PICO_SDK_CONFIG_QMK_H 